server:
  port: 9006

spring:
  application:
    name: PAGE-SERVICE
  datasource:
    url: jdbc:mysql:///hrm-page?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8
hrm:
  swagger:
    title: 页面静态化管理服务
    description: 页面静态化管理服务的接口文档

feign:
  hystrix:
    enabled: true
