server:
  port: 9527
zuul:
  prefix: /services
  ignored-services: "*"
  routes:
    system:
      path: /system/**
      serviceId: SYSTEM-SERVICE
    course:
      path: /course/**
      serviceId: COURSE-SERVICE
    file:
      path: /file/**
      serviceId: FILE-SERVICE


